name: Build UFORTH

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            output: ufo-linux
          - os: macos-latest
            output: ufo-macos
          - os: windows-latest
            output: ufo-windows.exe

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: gcc src/lexer.c src/compiler.c src/version.c src/main.c -o ${{ matrix.output }} -Iinclude

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}
